name: weather_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons:
  animated_splash_screen: ^1.1.0
  weather_icons: ^3.0.0
  get_it: ^3.0.0+1
  provider:
  http:
  intl: 
  scrollable_panel: ^0.4.1 
  flutter_svg: ^0.19.3
  jiffy: 
  google_place: ^0.3.3
  timeago: ^2.0.26
  location:
  google_maps_flutter:
  permission_handler:
  connectivity: ^3.0.4
  fluttertoast: ^8.0.7
  cached_network_image:
  geolocator:
  flutter_google_places:
  google_maps_webservice: ^0.0.19
  geoflutterfire:
  flutter_google_places_web:
  flushbar: ^1.10.4
  geocoding:
  ars_progress_dialog: ^0.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/weather.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
